/// Canonical KDX packet types, grouped by opcode range.
#[repr(u8)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum PacketType {
    // Connection management (0x00-0x0F)
    HandshakeInit = 0x01,
    HandshakeResp = 0x02,
    Ping = 0x03,
    Pong = 0x04,
    Disconnect = 0x0F,

    // Authentication (0x10-0x1F)
    AuthRequest = 0x10,
    AuthChallenge = 0x11,
    AuthResponse = 0x12,
    AuthResult = 0x13,

    // File operations (0x20-0x2F)
    FileListRequest = 0x20,
    FileListResponse = 0x21,
    FileTransferStart = 0x22,
    FileTransferData = 0x23,
    FileTransferEnd = 0x24,
    FileCreateFolder = 0x25,
    FileDelete = 0x26,
    FileGenerateCatalog = 0x27,
    FileCatalogGenerated = 0x28,
    FileSearchRequest = 0x29,
    FileSearchResponse = 0x2A,
    FileMove = 0x2B,

    // Chat (0x30-0x3F)
    ChatMessage = 0x30,
    ChatJoin = 0x31,
    ChatLeave = 0x32,
    ChatUserList = 0x33,
    ChatTopicSet = 0x34,

    // Presence (0x35-0x39)
    PresenceListRequest = 0x35,
    PresenceListResponse = 0x36,
    PresenceChange = 0x37,
    UserInfoRequest = 0x38,
    UserInfoResponse = 0x39,

    // Private messages (0x40-0x41)
    PrivateSend = 0x40,
    PrivateMessage = 0x41,
    // Admin: forcibly disconnect / ban a user (0x42)
    AdminDisconnect = 0x42,

    // Roles / account admin (0x50-0x58)
    RoleListRequest = 0x50,
    RoleListResponse = 0x51,
    RoleCreate = 0x52,
    RoleUpdate = 0x53,
    RoleDelete = 0x54,
    RoleAssign = 0x55,
    RoleUnassign = 0x56,
    AccountRolesRequest = 0x57,
    AccountRolesResponse = 0x58,
    AccountCreate = 0x59,
    AccountUpdate = 0x5A,
    AccountListRequest = 0x5B,
    AccountListResponse = 0x5C,

    // Public News (0x60-0x66)
    NewsgroupListRequest = 0x60,
    NewsgroupListResponse = 0x61,
    NewsThreadListRequest = 0x62,
    NewsThreadListResponse = 0x63,
    NewsPostCreate = 0x64,
    NewsPostDelete = 0x65,
    NewsgroupCreate = 0x66,

    // Tracker directory (0x70-0x71)
    TrackerListRequest = 0x70,
    TrackerListResponse = 0x71,

    // Remote server management (0x72-0x76)
    ServerSettingsRequest = 0x72,
    ServerSettingsResponse = 0x73,
    ServerSettingsUpdate = 0x74,
    AdminBroadcast = 0x75,
    AdminShutdown = 0x76,

    // Invite to a private chat (0x77-0x78) — logically part of Chat
    // (0x30-0x3F), but that block filled up before this feature existed.
    ChatInvite = 0x77,
    ChatInvited = 0x78,

    // System (0xF0-0xFF)
    Error = 0xF0,
    Warning = 0xF1,
    Info = 0xF2,
}

impl PacketType {
    pub const ALL: [PacketType; 66] = [
        PacketType::HandshakeInit,
        PacketType::HandshakeResp,
        PacketType::Ping,
        PacketType::Pong,
        PacketType::Disconnect,
        PacketType::AuthRequest,
        PacketType::AuthChallenge,
        PacketType::AuthResponse,
        PacketType::AuthResult,
        PacketType::FileListRequest,
        PacketType::FileListResponse,
        PacketType::FileTransferStart,
        PacketType::FileTransferData,
        PacketType::FileTransferEnd,
        PacketType::FileCreateFolder,
        PacketType::FileDelete,
        PacketType::FileGenerateCatalog,
        PacketType::FileCatalogGenerated,
        PacketType::FileSearchRequest,
        PacketType::FileSearchResponse,
        PacketType::FileMove,
        PacketType::ChatMessage,
        PacketType::ChatJoin,
        PacketType::ChatLeave,
        PacketType::ChatUserList,
        PacketType::ChatTopicSet,
        PacketType::PresenceListRequest,
        PacketType::PresenceListResponse,
        PacketType::PresenceChange,
        PacketType::UserInfoRequest,
        PacketType::UserInfoResponse,
        PacketType::PrivateSend,
        PacketType::PrivateMessage,
        PacketType::AdminDisconnect,
        PacketType::RoleListRequest,
        PacketType::RoleListResponse,
        PacketType::RoleCreate,
        PacketType::RoleUpdate,
        PacketType::RoleDelete,
        PacketType::RoleAssign,
        PacketType::RoleUnassign,
        PacketType::AccountRolesRequest,
        PacketType::AccountRolesResponse,
        PacketType::AccountCreate,
        PacketType::AccountUpdate,
        PacketType::AccountListRequest,
        PacketType::AccountListResponse,
        PacketType::NewsgroupListRequest,
        PacketType::NewsgroupListResponse,
        PacketType::NewsThreadListRequest,
        PacketType::NewsThreadListResponse,
        PacketType::NewsPostCreate,
        PacketType::NewsPostDelete,
        PacketType::NewsgroupCreate,
        PacketType::TrackerListRequest,
        PacketType::TrackerListResponse,
        PacketType::ServerSettingsRequest,
        PacketType::ServerSettingsResponse,
        PacketType::ServerSettingsUpdate,
        PacketType::AdminBroadcast,
        PacketType::AdminShutdown,
        PacketType::ChatInvite,
        PacketType::ChatInvited,
        PacketType::Error,
        PacketType::Warning,
        PacketType::Info,
    ];
}

impl TryFrom<u8> for PacketType {
    type Error = crate::ProtocolError;

    fn try_from(value: u8) -> Result<Self, crate::ProtocolError> {
        use PacketType::*;
        Ok(match value {
            0x01 => HandshakeInit,
            0x02 => HandshakeResp,
            0x03 => Ping,
            0x04 => Pong,
            0x0F => Disconnect,
            0x10 => AuthRequest,
            0x11 => AuthChallenge,
            0x12 => AuthResponse,
            0x13 => AuthResult,
            0x20 => FileListRequest,
            0x21 => FileListResponse,
            0x22 => FileTransferStart,
            0x23 => FileTransferData,
            0x24 => FileTransferEnd,
            0x25 => FileCreateFolder,
            0x26 => FileDelete,
            0x27 => FileGenerateCatalog,
            0x28 => FileCatalogGenerated,
            0x29 => FileSearchRequest,
            0x2A => FileSearchResponse,
            0x2B => FileMove,
            0x30 => ChatMessage,
            0x31 => ChatJoin,
            0x32 => ChatLeave,
            0x33 => ChatUserList,
            0x34 => ChatTopicSet,
            0x35 => PresenceListRequest,
            0x36 => PresenceListResponse,
            0x37 => PresenceChange,
            0x38 => UserInfoRequest,
            0x39 => UserInfoResponse,
            0x40 => PrivateSend,
            0x41 => PrivateMessage,
            0x42 => AdminDisconnect,
            0x50 => RoleListRequest,
            0x51 => RoleListResponse,
            0x52 => RoleCreate,
            0x53 => RoleUpdate,
            0x54 => RoleDelete,
            0x55 => RoleAssign,
            0x56 => RoleUnassign,
            0x57 => AccountRolesRequest,
            0x58 => AccountRolesResponse,
            0x59 => AccountCreate,
            0x5A => AccountUpdate,
            0x5B => AccountListRequest,
            0x5C => AccountListResponse,
            0x60 => NewsgroupListRequest,
            0x61 => NewsgroupListResponse,
            0x62 => NewsThreadListRequest,
            0x63 => NewsThreadListResponse,
            0x64 => NewsPostCreate,
            0x65 => NewsPostDelete,
            0x66 => NewsgroupCreate,
            0x70 => TrackerListRequest,
            0x71 => TrackerListResponse,
            0x72 => ServerSettingsRequest,
            0x73 => ServerSettingsResponse,
            0x74 => ServerSettingsUpdate,
            0x75 => AdminBroadcast,
            0x76 => AdminShutdown,
            0x77 => ChatInvite,
            0x78 => ChatInvited,
            0xF0 => Error,
            0xF1 => Warning,
            0xF2 => Info,
            other => return Err(crate::ProtocolError::UnknownPacketType(other)),
        })
    }
}
